swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: Login to continue services below or go to javascript%3Aalert(%27test%27)%3C%2Fp%3Elink%3Cp%3E

paths:
  /Login_Page:
    post:
      summary: Login here to continue
      description: Please provide your credentials to log in.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - <u>Click here to login</u>
      responses:
        '200':
          description: Successfully logged in and authenticated.
        '400':
          description: Invalid credentials or missing parameters.
        '500':
          description: Internal server error.
